name: Bug Report
description: Report a bug.
title: "[Bug]: "
labels:
  - bug
body:
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Go to '...', Click on '....', Scroll down to '....', See error
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
